### ISSUE TITLE
V1.0.1 Build Failure

### ISSUE THREAD

**Issue by ivujosevic** [aliab/RTLMaterialSpinner#5]
Log https://jitpack.io/com/github/aliab/RTLMaterialSpinner/V1.0.1/build.log

**Comment by aliab** [comment]
humm, seems JitPack has a bug in accepting licence
`You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 25.0.2, Android SDK Platform 25].`
I will change build tools and update library soon. thank's for your report.
